/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

	// https://mvnrepository.com/artifact/com.corundumstudio.socketio/netty-socketio
	implementation("com.corundumstudio.socketio:netty-socketio:2.0.9")
    implementation("com.hivemq:hivemq-mqtt-client:1.3.0")
     implementation("com.hivemq:hivemq-community-edition-embedded:2024.4")

    // https://mvnrepository.com/artifact/junit/junit
    testImplementation("junit:junit:4.13.2")
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0-M2")

    // https://mvnrepository.com/artifact/com.sun.net.httpserver/http
    implementation("com.sun.net.httpserver:http:20070405")





}

application {
    // Define the main class for the application.
    mainClass.set("server.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
